feat: use real text
freeCodeCamp/CurriculumExpansion pull request #311
Opened 2021-09-14 00:20 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

I may or may not have filched the text from [Quincy's original announcement](https://forum.freecodecamp.org/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) but thought it would be cool to have the campers write a "real" article instead of placeholder text.

2021-09-14 11:45 UTC, ShaunSHamilton requested changes
Do you use a Mac, Nich?

I like the look of the special characters, but they tend to mess up tests and old browsers.

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +                including Harvard’s CS50 and Stanford’s Database Class.
```suggestion
                including Harvard's CS50 and Stanford's Database Class.
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +                on General Assembly’s Dash course for these).
```suggestion
                We added our own HTML+CSS challenges (before we'd been relying
                on General Assembly's Dash course for these).
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          certification. They’ll get that sense of forward progress right from
```suggestion
          certification. They'll get that sense of forward progress right from
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          forth from “reading mode” to “coding mode”.
```suggestion
          forth from "reading mode" to "coding mode".
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          Instead of a series of coding challenges, you’ll learn through
```suggestion
          Instead of a series of coding challenges, you'll learn through
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          It wasn’t as dramatic as Doc’s revelation in Back to the Future. It
```suggestion
          It wasn't as dramatic as Doc's revelation in Back to the Future. It
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          individual coding challenges, we’ll just have projects, each with
```suggestion
          individual coding challenges, we'll just have projects, each with
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          hints if that isn’t enough.)
```suggestion
          hints if that isn't enough.)
```

2021-09-14 11:45 UTC, ShaunSHamilton commented on learn-css-grid-by-building-a-magazine/index.html
> +          projects. And there’s plenty of repetition to help you retain
```suggestion
          projects. And there's plenty of repetition to help you retain
```

2021-09-14 14:44 UTC, nhcarrigan commented
> Do you use a Mac, Nich?

No but when you copy-paste from the forum you get the forum's smart quotes lol

2021-09-14 20:33 UTC, ShaunSHamilton approved these changes
This LGTM 👍 

I am happy with this content. Perhaps just a ping for @QuincyLarson to approve the use of his words (I will send him a Chat too).

2021-09-15 06:04 UTC, QuincyLarson commented
@nhcarrigan Nice call. I had forgotten about the whole Back to The Future reference :) Thanks for updating this.

2021-09-15 06:04 UTC, merged