refactor: use tables
freeCodeCamp/CurriculumExpansion pull request #314
Opened 2022-01-04 23:15 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Discussion with @ShaunSHamilton regarding https://github.com/freeCodeCamp/freeCodeCamp/issues/44609 led to a suggestion to remove `tabindex`, and also convert this project to use HTML tables (which we do not teach elsewhere).

2022-01-05 08:56 UTC, ShaunSHamilton requested changes
Thank you, for tackling this, Nich.

I am going to be a pain and suggest some accessibility improvements - otherwise @bbsmooth will _be on our case_ 😉 

---

1) Give the table a `caption` element describing the table
2) Move the `Balance Sheet` and `freeCodeCamp` into their own `thead` element
3) Explicitly define where the `tbody` should be (otherwise HTML tries to guess where to put it)
4) OPTIONAL _because it is relatively advanced_ : Include `headers` and `scope` attributes for the `th` and `td` elements to relate essentially what is a tag/heading and what is a value.

2022-01-26 20:49 UTC, nhcarrigan commented
@ShaunSHamilton for some reason I had it in my head that you said you'd look at this. 🤦🏻‍♀️ 

Anyway, I've applied 1 2 and 3. 4 doesn't seem like it would fit well with the table structure, which *might* mean it's not a good table? 🤔 Also, any thoughts on how we want to style the caption?

2022-01-27 13:07 UTC, ShaunSHamilton commented
> for some reason I had it in my head that you said you'd look at this. 🤦🏻‍♀️

I think I did say this (on Chat, or something), and I did look into it, but never found a particularly nice way of doing things.

> which might mean it's not a good table?

It is an odd table.

How about, before we waste our time implementing stuff that might not be correct, we get another opinion? I will post this on the forum.

> Also, any thoughts on how we want to style the caption?

I am not sure about the accessibility of such, but I always prefer captions at the bottom:

```html
<caption style="caption-side:bottom">Caption describing table</caption>
```

2022-01-27 17:38 UTC, nhcarrigan commented
> How about, before we waste our time implementing stuff that might not be correct, we get another opinion? I will post this on the forum.

This is not a bad idea, tbh.

2022-02-02 12:31 UTC, ShaunSHamilton approved these changes
Well... LGTM 👍

2022-02-03 02:27 UTC, nhcarrigan commented
Gave this one final look. I think we might be missing a selector or two, but IMHO it's much more beneficial to teach good accessibility practises and HTML tables.

2022-02-03 04:04 UTC, merged

2022-02-03 04:04 UTC, nhcarrigan commented
Will break down into steps tomorrow