chore: add JS only higher order functions lab to frontend cert
freeCodeCamp/CurriculumExpansion pull request #586
Opened 2024-09-13 06:19 UTC by fhsinchy

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #519

2024-09-20 12:37 UTC, zairahira requested changes
This is a good practice project 👍️

I feel the instructions should be ordered like this because in one of the steps(updated step 3) the `sortByYear` is used before it is has been defined:


```md
You should have a callback function named `sortByYear` that accepts two books, `book1`, and `book2` as parameter for sorting the array.

The `sortByYear` function should return `-1` if the `release_year` of `book1` object is smaller than that of the `book2` object.

The `sortByYear` function should return `1` if the `release_year` of `book1` object is bigger than that of the `book2` object.

The `sortByYear` function should return `0` for all other scenarios.

You should have an array of objects named `books` where each object in the array should have a string `title`, another string `author_name`, and a number `release_year`.

You should call the `filter` higher-order function on the `books` array with a callback to filter out books written after a certain year such as 1950 and save the filtered array in a new array named `filteredBooks`.

You should call the `sort` higher order function by passing the `sortByYear` callback function
on the `filteredBooks` array to sort the books according to their `release_year` in ascending order and save the sorted array in a new array named `filteredBooksSorted`. 

You should call the `forEach` higher order function on the `filteredBooksSorted` array and print out the details of each book following the `<BOOK_TITLE> by <BOOK_AUTHOR> (<RELEASE_YEAR>)` format.

```

2024-09-20 12:37 UTC, zairahira commented on frontend-cert/js-projects/higher-order-functions/script.js
> +  if (book1.release_year < book2.release_year) {
To match the instruction:

```suggestion
  if (book1.release_year > book2.release_year) {
```

2024-09-20 12:37 UTC, zairahira commented on frontend-cert/js-projects/higher-order-functions/user-stories.md
> +You should call the filter higher-order function on the `books` array with a callback to filter out books written after a certain year such as 1950 and save the filtered array in a new array named `f
```suggestion
You should call the `filter` higher-order function on the `books` array with a callback to filter out books written after a certain year such as 1950 and save the filtered array in a new array named `filteredBooks`.
```

2024-09-20 12:37 UTC, zairahira commented on frontend-cert/js-projects/higher-order-functions/user-stories.md
> +You should call the `sort` higher order function on the `filteredBooks` array to filter the books according to their `release_year` in ascending order and save the filtered array in a new array named
```suggestion
You should call the `sort` higher order function by passing the `sortByYear` callback function on the `filteredBooks` array to sort the books according to their `release_year` in ascending order and save the sorted array in a new array named `filteredBooksSorted`.
```

2024-09-27 06:32 UTC, fhsinchy commented
@zairahira I have implemented the suggestion and now it's ready for another review.

2024-09-27 09:14 UTC, zairahira commented on frontend-cert/js-projects/higher-order-functions/user-stories.md
> +You should have an array of objects named `books` where each object in the array should have a string `title`, another string `author_name`, and a number `release_year`.
Maybe we can mention that "You should add at least 3 items to your array".

2024-09-27 09:15 UTC, zairahira approved these changes
Left one small suggestion, rest is good to go 👍️

2024-10-01 16:47 UTC, jdwilkin4 approved these changes
I went ahead and pushed up a change to include that last review comment.

This is good to go in

2024-10-01 16:47 UTC, merged